### ISSUE TITLE
Since one of the latest updates I've started getting strange errors: failed to open stream

### ISSUE THREAD

**Issue by pawlus** [mtoensing/lazy-loading-responsive-images#10]
Warning: getimagesize(**some file**): failed to open stream: HTTP request failed! HTTP/1.0 400 Bad request in /subdomains/blog/httpdocs/wp-content/plugins/lazy-loading-responsive-images/src/Plugin.php on line 231

My website: https://justmarried.com.pl

I'm using Porto 2 - it's flotheme. You will see error when you go e.g. here -> https://justmarried.com.pl/sesja-narzeczenska-na-gran-canaria/

There isn't any issue last week as I remember so one of the latest change started failing.. 
Do you know what's happen?

**Comment by florianbrinkmann** [comment]
Hey @pawlus,

sorry to hear that. The `getimagesize()` function is part of a new feature I added. Currently I have no idea why it is failing to load the image on your site, maybe some permission things from the CDN, I will release a new version shortly that should just call this function if the aspectratio option is enabled. After that I will try to find a real fix for that.

Thanks,
Florian

**Comment by florianbrinkmann** [comment]
Just uploaded the new version 3.3.2 that should fix your issue. If the update from the W.org repo does not show up quickly, you can download the version from the GitHub release page (the lazy-loading-responsive-images.zip): https://github.com/florianbrinkmann/lazy-loading-responsive-images/releases/tag/v3.3.2

Florian

**Comment by pawlus** [comment]
Hi @florianbrinkmann 
Just updated plugin and.. it's working fine now! Thanks a lot for your fast response!

Thanks and have a good weekend!
Pawel

**Comment by florianbrinkmann** [comment]
Great to hear that! 
By the way: I don’t know if it is because you have `WP_DEBUG` enabled or some setting on the server, but: maybe you should change it so the server does not publicly display PHP notices, warnings, and errors (or did you just switch a setting so I can see them?) :)

> Thanks and have a good weekend!

Thanks, you too!
Florian
