### ISSUE TITLE
Fill `src` attribute with a transparent image instead of removing it

### ISSUE THREAD

**Issue by ocean90** [mtoensing/lazy-loading-responsive-images#12]
The `modify_img_markup()` method currently removes the `src` attribute. This can lead to page jumps while the images are loading, at least in Chrome. To avoid this the image should have the width/height attributes and the src attribute should have a small placeholder image.
[Lazysizes](https://github.com/aFarkas/lazysizes#tip-specifying-image-dimensions-minimizing-reflows-and-avoiding-page-jumps
) uses `data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==` for that.

For testing I added this through ` $img->setAttribute( 'src', 'data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==' );` in `modify_img_markup()` and got a much better loading behaviour.

Is this something the plugin can do by default or is there a reason why the `src` attribute gets omitted?

**Comment by florianbrinkmann** [comment]
Hey @ocean90,

no specific reason for that, just removed it following the first examples in the lazysizes readme. I will give it a try and add it to the next release, if I don’t find an issue :)

**Comment by florianbrinkmann** [comment]
Added it and will release a new version with that soon :)

**Comment by ocean90** [comment]
Awesome, thank you!
