### ISSUE TITLE
getting error - Unexpected end tag

### ISSUE THREAD

**Issue by pawlus** [mtoensing/lazy-loading-responsive-images#13]
WP: 4.9.6
LazyLoading: the latest version

This error comes up after the latest update..

Warning: DOMDocument::loadHTML(): Unexpected end tag : p in Entity, line: 63 in /subdomains/blog/httpdocs/wp-content/plugins/lazy-loading-responsive-images/src/Plugin.php on line 162

to reproduce:
https://justmarried.com.pl/kontakt/

**Comment by florianbrinkmann** [comment]
Hi @pawlus,

thanks for the report. I replaced a lib with pure PHP behaviour in the new update, and the lib suppressed that type of errors and I forgot to migrate that. I will publish an update to fix that!

Best,
Florian

**Comment by florianbrinkmann** [comment]
@pawlus would you give the beta version (https://github.com/florianbrinkmann/lazy-loading-responsive-images/releases/tag/v3.3.7-beta.1 – the lazy-loading-responsive-images.zip) a try? That would be great!

Thanks,
Florian

**Comment by pawlus** [comment]
Hi Florian,

Unfortunately I’m out of the ‚office’ so will be able to check it later today:(

Wysłane z iPhone'a

**Comment by florianbrinkmann** [comment]
Hey @pawlus,

okay!
I got a similar issue reporting in the W.org support forum, and there the issue was fixed with the beta. I released it to W.org a few minutes ago, so you can directly install it via the backend. If that does not fix your warnings, just add a comment here :)

Best,
Florian

**Comment by pawlus** [comment]
works fine! thanks!

**Comment by florianbrinkmann** [comment]
Great to hear that! :)
