### ISSUE TITLE
FYI Plugin tested using the current version (4.1.5) of lazysizes, everything OK so far

### ISSUE THREAD

**Issue by diegocanal** [mtoensing/lazy-loading-responsive-images#19]
Hi Florian,

FYI, I've been testing the plugin using the current version (4.1.5) of:
<ul>
	<li>lazysizes.min.js</li>
	<li>ls.aspectratio.min.js</li>
	<li>ls.unveilhooks.min.js</li>
</ul>

Everything seems to be working fine so far. Perhaps it's time to update them from versions 4.0.3/4.0.4.

Best,
Diego

**Comment by florianbrinkmann** [comment]
Hey Diego,

thanks for the hint! Will do that in the next version, I already updated it to 4.1.4 here in the repo a few weeks back, will push it to 4.1.5.

Best,
Florian

**Comment by diegocanal** [comment]
Good, thanks Florian!

**Comment by florianbrinkmann** [comment]
Thank you for testing!

**Comment by florianbrinkmann** [comment]
A new version of Lazy Loader is live with lazysizes 4.1.5 :)

**Comment by diegocanal** [comment]
Awesome! Thanks for keeping me posted.
