### ISSUE TITLE
Improvement suggestion: safer version for the transparent GIF placeholder

### ISSUE THREAD

**Issue by diegocanal** [mtoensing/lazy-loading-responsive-images#20]
Hey Florian,

I can see you've fixed the missing srcset issue via [441f842](https://github.com/florianbrinkmann/lazy-loading-responsive-images/commit/441f8421aee2b0d9ec71962b10f5af1fcb0c2b05) –thank you very much!– but I can see that the safer version of the transparent GIF for the placeholder I suggested has not been implemented. My suggestion was to replace:

`data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw== `

by:

`data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7`

The argument to do so is explained in [https://stackoverflow.com/questions/6018611/smallest-data-uri-image-possible-for-a-transparent-image](https://stackoverflow.com/questions/6018611/smallest-data-uri-image-possible-for-a-transparent-image).

Best,
Diego

**Comment by florianbrinkmann** [comment]
Hi Diego,I did that in https://github.com/florianbrinkmann/lazy-loading-responsive-images/commit/9483d8bf1ad28101233ca37a5d47644994f8696d :)The reason I have not released a new version yet is that I have a problem with another new feature I want to add. I hope I will have time for this in the next days to get the new version with your suggestions live :)Best,Florian

**Comment by diegocanal** [comment]
Oops :o, I'd missed that commit, sorry.

I guess you're working on the background image support feature. Please, let me know if I can be of any help doing some testing –alphas, betas…whatever– .

Thanks!

**Comment by florianbrinkmann** [comment]
No problem :)

> I guess you're working on the background image support feature.

Unfortunately not, that is a bit more difficult:D But thanks for your offer, will keep that in mind! I’m working on allowing to disable the plugin on a per-page basis via a checkbox and have a problem with a filter there…

Best,
Florian
