### ISSUE TITLE
Options are not deleted from database on uninstall

### ISSUE THREAD

**Issue by florianbrinkmann** [mtoensing/lazy-loading-responsive-images#23]
It was reported that the options are not removed from the database on uninstall. Need to test this.

**Comment by diegocanal** [comment]
I've just tested it and I can confirm that options are not deleted from database on uninstall.

**Comment by florianbrinkmann** [comment]
Thanks for testing @diegocanal! Will take a look at it and try to find out why the uninstall function does not work like expected.
