### ISSUE TITLE
(native) WordPress audio shortcode crashes when placing an image on the same page/post

### ISSUE THREAD

**Issue by diegocanal** [mtoensing/lazy-loading-responsive-images#27]
Hi Florian,

If there are an image and an audio shortcode on the same page/post, the latest crashes, causing the audio player and the rest of the content that comes after it to disappear. For example:

`<p>Paragraph 1. This paragraph is NOT going to disappear</p><img src="https://mydomain.com/wp-content/uploads/image_file.png" alt="" width="300" height="225" class="alignnone size-medium wp-image-53" /><p>Paragraph 2. This paragraph is NOT going to disappear</p>[audio mp3="https://mydomain.com/wp-content/uploads/audio_file.mp3"][/audio]<p>Paragraph 3. This paragraph is going to disappear</p>`

Best Regards

**Comment by florianbrinkmann** [comment]
Hi @diegocanal,

thanks for reporting the issue! I will take a look at it.

Best,
Florian

**Comment by florianbrinkmann** [comment]
Hi @diegocanal,

I think I found the issue. Could you try the release here? https://github.com/florianbrinkmann/lazy-loading-responsive-images/releases/tag/v4.1.1-alpha.1 (it only is named alpha because I already know that it contains another bug that is not fixed there yet :) ).

Thanks,
Florian

**Comment by diegocanal** [comment]
Hi @florianbrinkmann,

I have tried the release, it works fine now.

Thanks very much! :)
Diego

**Comment by florianbrinkmann** [comment]
Hey Diego,

you’re welcome, thanks a lot for testing! :) Great to hear that it is fixed now.

Best,
Florian
