### ISSUE TITLE
Images from Gutenberg dynamic blocks

### ISSUE THREAD

**Issue by websupporter** [mtoensing/lazy-loading-responsive-images#29]
Gutenberg renders dynamic blocks by loading its content via the Rest API.

Currently:
`Helpers::is_admin_request()` does not recognize this as being an admin request. If this block contains an image, the image will be replaced and the block will not render correctly in Gutenberg.

Expected behavior:
The plugin should not replace the image, when Gutenberg tries to render a dynamic block.

**Comment by florianbrinkmann** [comment]
Thanks for opening the issue and for the PR! ❤️ I will take a look at it ASAP.
