### ISSUE TITLE
[Feature Request] Prevent lazy load when class is on wrapper element

### ISSUE THREAD

**Issue by lonix1** [mtoensing/lazy-loading-responsive-images#35]
The "CSS classes to exclude" option only works on an image - not when the image is a child element.

The block editor (gutenberg) creates this:

````html
<figure>
  <a ...>
    <img .../>
  </a>
</figure>
````

So when I apply a class - e.g. `not-lazy`, it will be applied to the `figure` element, not to the `img`.

Please allow us to stop lazy loading when the class is applied to a wrapper element?

**Comment by florianbrinkmann** [comment]
Hi @lonix1,

that is already possible, try the `disable-lazyload` class :)

Best,
Florian

**Comment by lonix1** [comment]
Thanks!
It would be helpful to include that info on the plugin page (settings > media). I incorrectly assumed I must define such a class myself ("CSS classes to exclude").

**Comment by florianbrinkmann** [comment]
You’re welcome.
It is part of the readme. The field in the settings is for classes that are defined on the `img` itself. For example, if you want to exclude the post thumbnails from lazy loading but you are not able to modify the markup. But yes, a hint that there is an additional option via `disable-lazyload` class might be helpful in that place, I will open an issue for that :)
