### ISSUE TITLE
fallback if JS is disabled

### ISSUE THREAD

**Issue by atomGit** [mtoensing/lazy-loading-responsive-images#39]
no images within a post/page are displayed, including post featured image, if user disables JS

please consider ability to fallback to standard WP gallery function if JS is disabled

LL 5.1.2
WP 5.3.2

**Comment by florianbrinkmann** [comment]
Hi @atomGit,

there is a fallback. Could you post a link to the website where you have the issue?

Best,
Florian

**Comment by atomGit** [comment]
hi Florian

here's an example page: `12bytes.org/photos/frozen`

i use Fast Velocity Minify, Cache Enabler and WP ImageViewer plugins, but i disabled these and emptied browser cache to test - i've tested several times and each time images won't load if JS id disabled

the only settings in LLRI that are enabled are...
Enable lazy loading for iframes
Enable lazy loading for videos

WP 5.3.2, twenty-sixteen
LL 5.1.2 from this repo (version after the invalid char fix)

**Comment by florianbrinkmann** [comment]
Hi @atomGit,

thanks for the link!
I disabled the JS in Firefox and see the images. There is a space under each image, because the theme overwrites the `display: none` for the images with the modified markup, but the images from the `noscript` are displayed correctly. Which browser and OS are you using?

Best,
Florian

**Comment by atomGit** [comment]
you're right

i'm using Firefox but with a heavily modified config - i can troubleshoot this myself

i never thought that my configuration could have led to a problem with images not displaying

sorry for the trouble - next time i'll do what i should have done this time; test with a clean browser profile

**Comment by florianbrinkmann** [comment]
No problem :)
