### ISSUE TITLE
Fitvids

### ISSUE THREAD

**Issue by albi** [mtoensing/lazy-loading-responsive-images#41]
Hi Florian,

erstmal Respekt für das geniale Plugin! Bis jetzt hab ich kein besseres entdeckt.

Habe jedoch ein kleines Problem mit eingebetteten iframes. Ich habe die Option aktiviert, dass iframes ebenso lazy geladen werden. Nun nutze ich aber das Fitvids JS http://fitvidsjs.com welches einen div wrapper um den iframe setzt mit einem padding um die Player von YouTube und Vimeo schön responsive zu machen.

Irgendwie funktioniert das jedoch nicht so richtig. Die iframes bekommen keine Höhe usw. Gibt es eine Callback-Möglichkeit ein Skript auszuführen wenn iframes geladen werden? Dann könnte ich das fitvids Skript nochmals abfeuern.

Gruss
Alex

**Comment by florianbrinkmann** [comment]
Hi Alex,

vielen Dank, freut mich, dass dir das Plugin gefällt :)

Ich hab mal im lazysizes-Repo geschaut und bin darüber auf das hier gekommen: https://github.com/davatron5000/FitVids.js/issues/258

Da ist auch ein Gist verlinkt, das das Problem wohl lösen sollte, hängt sich an `lazyloaded` dran. jQuery muss nicht sein, hier eine Beschreibung der vorhandenen JS-Events: https://github.com/aFarkas/lazysizes#js-api---events

Hoffe das hilft!

Viele Grüße
Florian

**Comment by albi** [comment]
Ach wie cool, an die Variante, also anders rum hab ich gar nicht gedacht. Das werd ich mal testen! Vielen Dank.

**Comment by florianbrinkmann** [comment]
Gerne!

**Comment by albi** [comment]
Läuft!
